### ISSUE TITLE
Cannot build on Fedora 36 ( arm64 )

### ISSUE THREAD

**Issue by Oein** [kentjhall/mizu#2]
When I run `make -j$(nproc)`
It ends with a error below.
```sh
In file included from ./core/loader/loader.h:18,
                 from core/hle/service/service.h:28,
                 from mizu.cpp:6:
./core/hle/kernel/code_set.h:11:10: fatal error: linux/horizon.h: No such file or directory
   11 | #include <linux/horizon.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by kentjhall** [comment]
You need to have the Horizon Linux kernel headers installed, using the `headers_install` target on the kernel source. Something like this (from the kernel source directory):
```
# make INSTALL_HDR_PATH=/usr headers_install
```
Mizu will only run under Horizon Linux, so the headers are necessary for building.
